//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    public partial class CustomerService
    {
        public int ConversationId { get; set; }
        public string RequestId { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string Context { get; set; }
        public string ResponseId { get; set; }
        public Nullable<bool> Read { get; set; }
    }
}
